"""Shared constants for plotting modules."""

DEFAULT_ALPHA = 0.8
ALPHA_HIGH = 0.9
ALPHA_MEDIUM = 0.6
GRID_ALPHA = 0.3
FILL_ALPHA = 0.2

FIGURE_SIZE_STANDARD = (12, 8)
FIGURE_SIZE_WIDE = (14, 8)
FIGURE_SIZE_NARROW = (8, 5)
FIGURE_SIZE_TALL = (10, 8)
FIGURE_SIZE_COMBINED = (14, 6)

MARKER_SIZE_SMALL = 2
MARKER_SIZE_MEDIUM = 3
MARKER_SIZE_STANDARD = 4
MARKER_SIZE_LARGE = 6
MARKER_SIZE_HIGHLIGHT = 150
SCATTER_SIZE = 5

LINE_WIDTH = 2
LINE_WIDTH_THIN = 1.5
LINE_WIDTH_BOLD = 2.5
LINE_WIDTH_EXTRA_BOLD = 3
LINE_WIDTH_EDGE = 0.5

COLOR_ENCODER = "blue"
COLOR_DECODER = "orange"
COLOR_KL = "red"
COLOR_TOTAL = "purple"
COLOR_REALIZED = "green"
COLOR_UNCLIPPED = "gray"
COLOR_COSINE = "purple"
COLOR_TOTAL_ENCODER = "purple"
COLOR_TOTAL_DECODER = "green"
COLOR_ACTIVE = "steelblue"
COLOR_INACTIVE = "red"
COLOR_THRESHOLD = "red"
COLOR_GRAY = "gray"
COLOR_PURPLE = "purple"
COLOR_EARLY = "lightblue"
COLOR_MIDDLE = "orange"
COLOR_FINAL = "red"
COLOR_START = "green"
COLOR_START_EDGE = "darkgreen"
COLOR_END = "red"
COLOR_END_EDGE = "darkred"
COLOR_BEST = "gold"
COLOR_BEST_EDGE = "darkorange"
COLOR_LEARNING_RATE = "purple"
COLOR_RECONSTRUCTION = "orange"

DEFAULT_CMAP = "tab10"
CMAP_PROGRESS = "coolwarm"

LABEL_FONTSIZE = 12
TITLE_FONTSIZE = 14
SMALL_FONTSIZE = 9
BAR_LABEL_FONTSIZE = 8

MAX_DIMS_FOR_LABELS = 20
MAX_DIMS_SINGLE_COLUMN = 5
MAX_EPOCHS_FULL_TICKS = 15
HEATMAP_TICK_DIVISIONS = 8

ZORDER_HIGHLIGHT = 10
ZORDER_BEST = 15
